// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// Trigger HMR

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['main']['BlogService']['CreateCategory'](arg1, arg2, arg3);
}

export function CreatePost(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['BlogService']['CreatePost'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTag(arg1) {
  return window['go']['main']['BlogService']['CreateTag'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['BlogService']['DeleteCategory'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['BlogService']['DeleteComment'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['main']['BlogService']['DeletePost'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['BlogService']['DeleteTag'](arg1);
}

export function GetAllComments() {
  return window['go']['main']['BlogService']['GetAllComments']();
}

export function GetAllPosts() {
  return window['go']['main']['BlogService']['GetAllPosts']();
}

export function GetCategories() {
  return window['go']['main']['BlogService']['GetCategories']();
}

export function GetPostByID(arg1) {
  return window['go']['main']['BlogService']['GetPostByID'](arg1);
}

export function GetPostBySlug(arg1) {
  return window['go']['main']['BlogService']['GetPostBySlug'](arg1);
}

export function GetPublishedPosts(arg1, arg2) {
  return window['go']['main']['BlogService']['GetPublishedPosts'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['BlogService']['GetStats']();
}

export function GetTags() {
  return window['go']['main']['BlogService']['GetTags']();
}

export function UpdateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['BlogService']['UpdateCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateCommentStatus(arg1, arg2) {
  return window['go']['main']['BlogService']['UpdateCommentStatus'](arg1, arg2);
}

export function UpdatePost(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['BlogService']['UpdatePost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
