// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreatePost(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Array<string>,arg6:string):Promise<void>;

export function CreateTag(arg1:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeletePost(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetAllComments():Promise<Array<main.CommentDTO>>;

export function GetAllPosts():Promise<Array<main.PostDTO>>;

export function GetCategories():Promise<Array<main.Category>>;

export function GetPostByID(arg1:number):Promise<main.Post>;

export function GetPostBySlug(arg1:string):Promise<main.PostDTO>;

export function GetPublishedPosts(arg1:number,arg2:number):Promise<Array<main.PostDTO>>;

export function GetStats():Promise<any>;

export function GetTags():Promise<Array<any>>;

export function UpdateCategory(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateCommentStatus(arg1:number,arg2:string):Promise<void>;

export function UpdatePost(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<string>,arg7:string):Promise<void>;
