// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUploadDir() {
  return window['go']['main']['UploadService']['GetUploadDir']();
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['UploadService']['UploadImage'](arg1, arg2);
}
